### DISCUSSION TITLE
Including from URL & Cache

### DISCUSSION THREAD

**Discussion by dpapagiannis** [mondeja/mkdocs-include-markdown-plugin#260] [Q&A] [answered]
Hello!

I would like to ask about the expected behavior of using `cache` along with `.md` files included from HTTP links.

I have used the following directive:

```
{%
include-markdown "https://link/to/md"
%}
```

Along with the following config:

```yaml
plugins:
  - include-markdown:
      cache: 1  # Small so that updates to the remote file are reflected immediately
```

and I have the `cache` extras installed. 

If I start the server (`mkdocs serve`), the remote file is fetched and displayed correctly. 

When I update the remote file, the rendered page including it does _not_ render the updated file, no matter how long I wait (expecting the cache to be invalidated within 1 second). It only updates when I restart the server.

Is this the expected behavior? Am I missing something?

Thanks a lot!
