### ISSUE TITLE
Can `exclude` be a list? To exclude multiple different files?

### ISSUE THREAD

**Issue by flynneva** [mondeja/mkdocs-include-markdown-plugin#172]
Something like:

```
plugins:
   - include-markdown:
       exclude:
         - LICENSE.md
         - some_other.md
```
