### ISSUE TITLE
Some clarification on heading_offset

### ISSUE THREAD

**Issue by aleray** [mondeja/mkdocs-include-markdown-plugin#200]
Hi,

Thanks for you plugin! I'm testing the plugin and I don't manage to do one thing: I'd like to use the heading_offset option to set it for each include by default:

So here is my config:

```yaml
site_name: Foo
plugins:
  - include-markdown:
      heading_offset: 2
```
And my index.md:

```md
{% include-markdown './included.md' start='<--start-->' %}
```

and the 

```md
Some ignored content.

<--start-->

Some included content.


# My heading
```

I'd like `My heading` to be and `<h3>` but it doesn't seem to work here.

Could you tell me if it is a bug or if I misunderstood the doc?

Thanks
