### ISSUE TITLE
pymdownx.tabbed is broken using mkdocs-include

### ISSUE THREAD

**Issue by SPyofgame200** [mondeja/mkdocs-include-markdown-plugin#202]
When I using mkdocs-include for the examples with tabbed

![image](https://github.com/mondeja/mkdocs-include-markdown-plugin/assets/52689671/91c59c85-bb9f-4890-8e83-8bb0cad92e3c)

I got a broken tabbed, which look like this

![image](https://github.com/mondeja/mkdocs-include-markdown-plugin/assets/52689671/fd76b503-f517-463f-aaac-5e84e3e08824)

when it is expected to work like this

![image](https://github.com/mondeja/mkdocs-include-markdown-plugin/assets/52689671/c71960e7-b344-4d4a-9410-8cdf80b76c07)

The setting I am using

```yml
  - include-markdown:
      opening_tag: "{{{!"
      closing_tag: "!}}}"
#     encoding: ascii
      dedent: false
      comments: false
      heading_offset: 0
      trailing_newlines: false
      rewrite_relative_urls: true
      preserve_includer_indent: true
```
