### ISSUE TITLE
Enabling this kills the search text input in the readthedocs theme

### ISSUE THREAD

**Issue by mattip** [mondeja/mkdocs-include-markdown-plugin#24]
I was wondering why the [cibuildwheel site](https://cibuildwheel.readthedocs.io/en/stable/) has no search input. So I created a minimal reproducer mkdocs.yml
```
site_name: My Docs
theme:
  name: readthedocs

plugins:
  - include-markdown
```

With the last two lines: no search box. Without them, search box appears. Any ideas?

**Comment by mondeja** [comment]
If I'm not wrong, you need to explicitly specify the plugin `search` in the `plugins` object because (I think) the default plugins are overwritten:

```yaml
site_name: My Docs
theme:
  name: readthedocs

plugins:
  - include-markdown
  - search
```

That works for me, the search bar reappears, could you confirm if works for you as well?
