### ISSUE TITLE
Internal anchor in included relative not being rewritten

### ISSUE THREAD

**Issue by mondeja** [mondeja/mkdocs-include-markdown-plugin#266]
Hello @mondeja , I'm seeing a similar problem as well when setting a `site_url`.

Given this structure:

```
tree website2
website2
├── docs
│   ├── index.md
│   └── other.md
└── mkdocs.yml

2 directories, 3 files
```

This `mkdocs.yml` file:

```yaml
site_name: My Docs
site_url: "https://example.com/org-name/repo-name/"

nav:
  - A section:
      An article: other.md

plugins:
  - include-markdown:
      rewrite_relative_urls: true
```

This markdown include:

```md
{%
   include-markdown "../../test.md"
%}
```

And this markdown file:

```md
# Header
# First level heading
Example data
## Second level heading
Link to [second level heading](#second-level-heading).
```

The URL generated is incorrect as shown below, causing 404s for local anchors
<img width="2032" alt="image" src="https://github.com/user-attachments/assets/57b41f47-ed3d-41ca-8915-d72d0b5ffbbf" />

I'm also seeing the following warnings in the build:

```
INFO    -  Doc file 'index.md' contains an unrecognized relative link '../../#second-level-heading', it was left as is.
INFO    -  Doc file 'other.md' contains an unrecognized relative link '../../#second-level-heading', it was left as is.
```

I'm using version `7.1.5` of the plugin

_Originally posted by @AlessandroPomponio in https://github.com/mondeja/mkdocs-include-markdown-plugin/discussions/253#discussioncomment-13458400_
