### ISSUE TITLE
allow user to change default delimiter

### ISSUE THREAD

**Issue by fwang2002** [mondeja/mkdocs-include-markdown-plugin#73]
It's better to allow user to change the default delimiter {% %}, which is conflict with mkdocs-macros-plugin.
Currently, when using this plugin, it must be configured before macros to let mkdocs work.

**Comment by mondeja** [comment]
You only need to change the plugins list and define `mkdocs-include-markdown` before macros, for example:

```yaml
plugins:
  - search:
      lang: en
  - include-markdown
  - macros:
      module_name: docs_macros
```

You can see a real open source project using this configuration [here](https://github.com/mondeja/http-request-codegen/blob/4597b697b080b8f2ba5b8d77f4949f767009365c/mkdocs.yml#L42).

I'm against change this, do you have any problems with the above configuration? Anyways, it seems that this should be documented.
